### ISSUE TITLE
Suggestion: Command Chance + printers + scrappers spawning

### ISSUE THREAD

**Issue by DaltonGoesFast** [Cercain/ImprovedCommandEssence#1]
Hey, sorry, I would have sent a message on discord but i could not find the username listed on the thunder store page. 
Extra configs to allow printers and scrappers to spawn on stages while command is active as well as a config for the chance for an item to be a command essecense would make this the perfect mod! thank you!!

**Comment by Cercain** [comment]
Those are great ideas!
I'll put them on my to do list, thanks!

**Comment by Cercain** [comment]
These suggestions have been added to 1.2.0
