### ISSUE TITLE
item bug

### ISSUE THREAD

**Issue by fruitytoast** [Cercain/ImprovedCommandEssence#11]
Sometimes with green essence a few of the items show up as a blank white square with "???" as the name. When clicked no item drops.

**Comment by fruitytoast** [comment]
any update please?

**Comment by Cercain** [comment]
Unable to replicate this.
Possibly a bug with another mod that they fixed?

**Comment by Cercain** [comment]
This may have been a compatibility issue it had with Starstorm 2 https://github.com/Cercain/ImprovedCommandEssence/issues/13
