### ISSUE TITLE
Incompatibility issue with Starstorm 2

### ISSUE THREAD

**Issue by Apaples** [Cercain/ImprovedCommandEssence#13]
I'm hoping you'd be willing to help me with getting your mod to work with Starstorm 2.  There is a bug when both mods are installed where Green Essence that come from defeating the teleporter event boss include these invalid White box choices.

![Startstorm2](https://user-images.githubusercontent.com/125098507/218221295-4d747f89-2d11-41e0-aa84-b0b040809348.png)

If you select one, it does spawn in the world.  It is invisible but a prompt exists that says "Pick Up ???"  Pressing the interact key does not pick anything up.  

This issue does not occur with most Green Essences , only those dropped by bosses.  A boss Green will randomly have an amount of these white boxes.  Rarely having all regular items, often having 1 or 2 white boxes, and occasionally having only white boxes as choices.  

I'm not sure which mod is at 'fault' for this incompatibility.  I have hunches on what might be causing it, but as a complete novice, I doubt they'd be very useful.

If you're willing to look into this, I would appreciate it.  I'm happy to help in any way I can.  You can contact me via discord. 
@ apples#1807.  I am in the modding discord and have open PMs

**Comment by Apaples** [comment]
Changing SameBossDrop to False Bypasses this issue.  So, perhaps something in your code that ensures the boss drops are the same causes the problem. I don't know if other new item mods cause this same issue.

**Comment by Darkmega18** [comment]
ah. so this can be fixed with a config? wonderful.

**Comment by Cercain** [comment]
Hey, sorry for such a late response, finally catching up on these.

Were you able to figure this one out?
When `SameBossDrop` is enabled I hook into the `BossGroup.DropRewards` event, if your mod is adding items to `BossGroup.dropTable` that could be where it is pulling those from

**Comment by Cercain** [comment]
I've not been able to replicate this, StarStorm 2 may have fixed the issue causing this?

**Comment by Cercain** [comment]
ah nvm was able to repro

**Comment by Cercain** [comment]
fixed in 1.3.3
