### ISSUE TITLE
Issue with special item from Forgotten Relics

### ISSUE THREAD

**Issue by Darkmega18** [Cercain/ImprovedCommandEssence#14]
Forgotten relics adds a special interactable to the world that is meant to drop a specific item. A certain "Relic of Energy". When interacted with while this mod is active the relic of energy is converted into a boss drop and cannot be selected from the command essence, unlike something like halcyon seed.
But without this mod enabled the relic will drop like normal, as I had turned the mod off to use full command recently to do some challenges.

Can this be looked into fixing?

**Comment by Cercain** [comment]
fixed in 1.3.4

**Comment by Darkmega18** [comment]
naisu
