### ISSUE TITLE
Requests and Feedback (Aspects Options)

### ISSUE THREAD

**Issue by MushroomEl** [Cercain/ImprovedCommandEssence#18]
Hello author, thank you for your work, I like this mod very much.
In addition, I would like to ask if you can add a function so that the artifact does not work on the printer.
And the artifact does not seem to work on elite items. I use the mod: TricornEliteEquipment, and the elite items dropped after killing the elite have no additional options.

**Comment by Cercain** [comment]
Hey, thanks for enjoying the mod.
In the configuration 'enablePrinters' will enable printers to spawn if true, and then you will need to make sure 'onInDropShip' is set to false. Printers will then drop their items, as will other Terminal type containers (Drop Ships, Multi Terminal, etc)

As for 'TricornEliteEquipment', I will look to add official compatibility with that mod

**Comment by Cercain** [comment]
Can I just check, is it that you want to have all other other elite equipment as an option when it drops, rather than just the one item?

**Comment by MushroomEl** [comment]
Yeah I wish elite items had all the options, but right now they just drop items directly.
Thank you very much for your work.

**Comment by MushroomEl** [comment]
I started the game with only this mod added, but the printer still can't drop items directly. This is my configuration file.
I changed the suffix to txt so that I can upload it.
[ImprovedCommandEssence.txt](https://github.com/user-attachments/files/15598913/ImprovedCommandEssence.txt)

**Comment by Cercain** [comment]
Ok, I found the bug there. It will be fixed in the next version, but for now you can set 'onForHidden' to true and it will be fixed.

I'll look into having options for aspects, but unfortunately they don't have a good tagging system, I can hard code it, but that will break compatibility with mods that have new aspects

**Comment by Cercain** [comment]
Added the fix to 1.4.0.
Still looking into the Aspects feature for this, might not be a possibility as there's things blocking Aspects from showing in command essences

**Comment by MushroomEl** [comment]
Yes, now the printer can drop items directly.
Thank you.
I found that the mod: BetterCommandArtifact can achieve elite item drops with all options, but the number of options is not affected by the configuration file. Maybe it is not adapted to the mod: TricornEliteEquipment, but it does not affect it.

**Comment by Cercain** [comment]
thanks, I'll take a look into what that one does

**Comment by Cercain** [comment]
Just added this as an option for 1.4.2
