### ISSUE TITLE
Incompatible with Ephemeral Coins

### ISSUE THREAD

**Issue by ConqAra** [Cercain/ImprovedCommandEssence#2]
When artifact of command is enabled with your mod, any lunar coin drops altered by Ephemeral Coins mod will not spawn, only makes the sound but no lunar coin is present.

Mod: [https://thunderstore.io/package/VarnaScelestus/Ephemeral_Coins/](https://thunderstore.io/package/VarnaScelestus/Ephemeral_Coins/)

**Comment by Cercain** [comment]
This seems to have just been a complete incompatibility with lunar coins in general, will be fixed in the 1.1.1 release
