### ISSUE TITLE
Multiplayer Non-Host Command Essence is Invisible

### ISSUE THREAD

**Issue by FantasticChimni** [Cercain/ImprovedCommandEssence#20]
Command essence is now invisible to anyone that is not the host of the game when it spawns.

To Reproduce
1. Host MP game with 1+ other players
2. Open chests until command essence drops
3. Host can see/interact
4. Have friend in game confirm they cannot see or interact with it.

**Comment by Cercain** [comment]
do all players have the mod?

Edit: Confirmed this occurs even when all players have the mod

**Comment by Cercain** [comment]
This should be fixed in 1.4.3
