### ISSUE TITLE
The Items you get from completeing a Cell in the Void Field are broken

### ISSUE THREAD

**Issue by Sanserio** [Cercain/ImprovedCommandEssence#22]
When you select the dropped items you get from completeing a void cell it's straight up blank, you can't get it, it'd be great if there was an option to disable Command from affecting the item drops from those cells entierly so they can actually function

**Comment by Cercain** [comment]
I'm hoping to take a look into this this week

**Comment by Sanserio** [comment]
Thank you so muchh me and my friends can't wait we don't play ror2 without this mod anymore

**Comment by Cercain** [comment]
I've managed to get these working in 1.4.4. They now drop as the void potential they would have in with no artifact.
It's not the solution I'd have liked, as I would prefer it to be affected by the configs of the mods, but the vanilla code handling this is very awkward.

I'm going to keep this issue open, and hopefully I can work a way to incorporate the configs to those drops.

**Comment by khdtheryu** [comment]
I just tested out 1.4.4 and the issue persists for me. Void potential drops, when you open it, there is only 1 blank item. When you click it, the void potential goes completely blank and you can no longer interact with it. Maybe I should change something in the config? I had no issues with void potentials prior to couple of mod updates I believe.

**Comment by Cercain** [comment]
Strange, it worked fine when I tested, what is your config?

**Comment by khdtheryu** [comment]
Attached txt version of my config
[ImprovedCommandEssence.txt](https://github.com/user-attachments/files/16034512/ImprovedCommandEssence.txt)

**Comment by Cercain** [comment]
I just completed all 9 cells successfully with your config, what other mods have you got?

**Comment by Cercain** [comment]
Ah ok, the cells complete, but the void triple chests that drop normal void potentials drop as you describe

**Comment by Cercain** [comment]
If you change the config value onForPotential to false, it should work to drop as a potential and use those config amounts.
True should make it drop as a command essence, but that's currently bugged

**Comment by khdtheryu** [comment]
Okay, that will do for now, thank you. Hopefully you can find a way to fix this.

**Comment by Cercain** [comment]
I think I've found the issue, I changed the way that items are selected for the Command Essence in 1.4.2, and that new way conflicts with Void Potentials.
I'll revert that and get another version pushed once I've confirmed thats a fix

**Comment by Cercain** [comment]
Pushed 1.4.5 which fixes this now.
Thanks for raising this, this mod has got so big I really need to start a test plan for every release >.<
Also reverted the half-fix for Cell rewards, as this actually addressed that too, so closing the issue now

**Comment by Cercain** [comment]
I prefer to play with onForPotential = false as the potentials have a mix of rarities, so this wouldnt have been caught with my regular testing play

**Comment by khdtheryu** [comment]
Glad to know I was somewhat of help. And thank you once again, for your mod and your time.
