### ISSUE TITLE
Incompatible with Zet Aspects

### ISSUE THREAD

**Issue by ConqAra** [Cercain/ImprovedCommandEssence#3]
When artifact of command is enabled with your mod, it doesn't ignore the zet aspects drops from elites and instead will convert it instead into a normal boss essence which won't include any of the aspects. This instance may not be your mod's fault, as I made the same issue on Zet aspects github as well.

**Comment by Cercain** [comment]
Aspect equipment was not dropping correctly as it should always give you just the aspect (as it does in vanilla) this is fixed in 1.1.1
However Zet Aspect's mode to turn them into Red items is trickier to fix, I will keep looking into this for you and hopefully find a resolution

**Comment by ConqAra** [comment]
Thank you!

**Comment by Cercain** [comment]
Sorted a fix for ZetAspects item drop mode now, probably a neater way to do it, but it works in 1.1.2
