### ISSUE TITLE
[BUG/QOL] Aurelionite's drop essence does not include Halcyon Seed

### ISSUE THREAD

**Issue by ConqAra** [Cercain/ImprovedCommandEssence#5]
After defeating Aurelionite, the yellow essence does not include Halcyon Seed. I feel like it should either include the Halcyon Seed in the yellow essence on the drop or have his drop be unaffected by artifact of command, always dropping a Halcyon Seed instead of a yellow essence.

**Comment by Cercain** [comment]
Fixed in 1.1.3
