### ISSUE TITLE
Regen Scrap Bug (Incompatibility for LittleGameplayTweaks...?)

### ISSUE THREAD

**Issue by ConqAra** [Cercain/ImprovedCommandEssence#7]
When using artifact of command with your mod, Teleporter sometimes doesn't give essence with[ LittleGameplayTweaks](https://thunderstore.io/package/Wolfo/LittleGameplayTweaks/) installed. This is probably something with the "boss items now having a 25% chance to drop from a teleporter instead of 15%" change from LittleGameplayTweaks mod, but that's just a guess. Please look into it! For example, when a teleporter item drops, instead of a green essence a regenerative scrap will spawn for some reason instead, and sometimes (usually with 2 shrine of the mountain activated) there will be non-essence boss items spawned at the teleporter as a reward instead.

**Comment by Cercain** [comment]
I'll take a look into this, but as they dont have any source code listed it might be tricky

**Comment by ConqAra** [comment]
Yeah wait, even in chests, not just teleporter items, if the game decided what would've been in that chest was regen scrap, it will still drop only the regen scrap instead. it won't drop a command essence no matter what. This might still be a weird incompatibility issue but if I can try playing enough with artifact of command on with your mod without LittleGameplayTweaks and the same thing happens, I'll let you know.

**Comment by Cercain** [comment]
Could you submit the logfile the next time you see this happen?
Logs files can be found in {r2modman folder}/RiskOfRain2/Profiles/{profile name}/BepInEx/LogOutput.log
The log resets so make sure you create a copy before starting a new run or relaunching the game

**Comment by Cercain** [comment]
Issue was found to be an incompatibility with mods that add items, I've reworked the code to use the proper method for checking against items and this is now fixed in 1.2.1
